version: '3.9'

services:
  
  app-wrapper:
    env_file:
      - dev.env
    image: hackathon/qcpdf-python
    volumes:
      - ./data:/service/data
    container_name: hackathon-qcpdf-python
    build:
      context: .
      dockerfile: ./Dockerfile_arm64 # change to Dockerfile on Linux
    entrypoint: /service/main
